const LEAD_STATUSES = {
  NEW_LEAD: 'NEW_LEAD',
  CONTACTED: 'CONTACTED',
  EMAIL_SENT: 'EMAIL_SENT',
  FOLLOW_UP_REQUIRED: 'FOLLOW_UP_REQUIRED',
  INTERESTED: 'INTERESTED',
  MEETING_SCHEDULED: 'MEETING_SCHEDULED',
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  NEGOTIATION: 'NEGOTIATION',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
};

const LEAD_STATUS_LABELS = {
  NEW_LEAD: 'New Lead',
  CONTACTED: 'Contacted',
  EMAIL_SENT: 'Email Sent',
  FOLLOW_UP_REQUIRED: 'Follow Up Required',
  INTERESTED: 'Interested',
  MEETING_SCHEDULED: 'Meeting Scheduled',
  PROPOSAL_SENT: 'Proposal Sent',
  NEGOTIATION: 'Negotiation',
  CLOSED_WON: 'Closed Won',
  CLOSED_LOST: 'Closed Lost',
};

module.exports = { LEAD_STATUSES, LEAD_STATUS_LABELS };
